version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/docs/examples/error_handler/error_handler_0"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/docs/examples/error_handler/error_handler_1"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/exporter/opentelemetry-exporter-jaeger"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/exporter/opentelemetry-exporter-jaeger-proto-grpc"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/exporter/opentelemetry-exporter-jaeger-thrift"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/exporter/opentelemetry-exporter-opencensus"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/exporter/opentelemetry-exporter-otlp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/exporter/opentelemetry-exporter-otlp-proto-grpc"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/exporter/opentelemetry-exporter-otlp-proto-http"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/exporter/opentelemetry-exporter-prometheus"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/exporter/opentelemetry-exporter-zipkin"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/exporter/opentelemetry-exporter-zipkin-json"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/exporter/opentelemetry-exporter-zipkin-proto-http"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/opentelemetry-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/opentelemetry-proto"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/opentelemetry-sdk"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/opentelemetry-semantic-conventions"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/propagator/opentelemetry-propagator-b3"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/propagator/opentelemetry-propagator-jaeger"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/shim/opentelemetry-opentracing-shim"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/tests/opentelemetry-test-utils"
    schedule:
      interval: "weekly"

