"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class TraceConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CONSTANT_SAMPLER_FIELD_NUMBER: builtins.int
    TRACE_ID_RATIO_BASED_FIELD_NUMBER: builtins.int
    RATE_LIMITING_SAMPLER_FIELD_NUMBER: builtins.int
    MAX_NUMBER_OF_ATTRIBUTES_FIELD_NUMBER: builtins.int
    MAX_NUMBER_OF_TIMED_EVENTS_FIELD_NUMBER: builtins.int
    MAX_NUMBER_OF_ATTRIBUTES_PER_TIMED_EVENT_FIELD_NUMBER: builtins.int
    MAX_NUMBER_OF_LINKS_FIELD_NUMBER: builtins.int
    MAX_NUMBER_OF_ATTRIBUTES_PER_LINK_FIELD_NUMBER: builtins.int
    max_number_of_attributes: builtins.int = ...
    max_number_of_timed_events: builtins.int = ...
    max_number_of_attributes_per_timed_event: builtins.int = ...
    max_number_of_links: builtins.int = ...
    max_number_of_attributes_per_link: builtins.int = ...

    @property
    def constant_sampler(self) -> global___ConstantSampler: ...

    @property
    def trace_id_ratio_based(self) -> global___TraceIdRatioBased: ...

    @property
    def rate_limiting_sampler(self) -> global___RateLimitingSampler: ...

    def __init__(self,
        *,
        constant_sampler : typing.Optional[global___ConstantSampler] = ...,
        trace_id_ratio_based : typing.Optional[global___TraceIdRatioBased] = ...,
        rate_limiting_sampler : typing.Optional[global___RateLimitingSampler] = ...,
        max_number_of_attributes : builtins.int = ...,
        max_number_of_timed_events : builtins.int = ...,
        max_number_of_attributes_per_timed_event : builtins.int = ...,
        max_number_of_links : builtins.int = ...,
        max_number_of_attributes_per_link : builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"constant_sampler",b"constant_sampler",u"rate_limiting_sampler",b"rate_limiting_sampler",u"sampler",b"sampler",u"trace_id_ratio_based",b"trace_id_ratio_based"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"constant_sampler",b"constant_sampler",u"max_number_of_attributes",b"max_number_of_attributes",u"max_number_of_attributes_per_link",b"max_number_of_attributes_per_link",u"max_number_of_attributes_per_timed_event",b"max_number_of_attributes_per_timed_event",u"max_number_of_links",b"max_number_of_links",u"max_number_of_timed_events",b"max_number_of_timed_events",u"rate_limiting_sampler",b"rate_limiting_sampler",u"sampler",b"sampler",u"trace_id_ratio_based",b"trace_id_ratio_based"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"sampler",b"sampler"]) -> typing_extensions.Literal["constant_sampler","trace_id_ratio_based","rate_limiting_sampler"]: ...
global___TraceConfig = TraceConfig

class ConstantSampler(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _ConstantDecision(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ConstantDecision.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        ALWAYS_OFF = ConstantSampler.ConstantDecision.V(0)
        ALWAYS_ON = ConstantSampler.ConstantDecision.V(1)
        ALWAYS_PARENT = ConstantSampler.ConstantDecision.V(2)
    class ConstantDecision(metaclass=_ConstantDecision):
        V = typing.NewType('V', builtins.int)
    ALWAYS_OFF = ConstantSampler.ConstantDecision.V(0)
    ALWAYS_ON = ConstantSampler.ConstantDecision.V(1)
    ALWAYS_PARENT = ConstantSampler.ConstantDecision.V(2)

    DECISION_FIELD_NUMBER: builtins.int
    decision: global___ConstantSampler.ConstantDecision.V = ...

    def __init__(self,
        *,
        decision : global___ConstantSampler.ConstantDecision.V = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"decision",b"decision"]) -> None: ...
global___ConstantSampler = ConstantSampler

class TraceIdRatioBased(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SAMPLINGRATIO_FIELD_NUMBER: builtins.int
    samplingRatio: builtins.float = ...

    def __init__(self,
        *,
        samplingRatio : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"samplingRatio",b"samplingRatio"]) -> None: ...
global___TraceIdRatioBased = TraceIdRatioBased

class RateLimitingSampler(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    QPS_FIELD_NUMBER: builtins.int
    qps: builtins.int = ...

    def __init__(self,
        *,
        qps : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"qps",b"qps"]) -> None: ...
global___RateLimitingSampler = RateLimitingSampler
