receivers:
  opencensus:
    endpoint: "0.0.0.0:55678"

exporters:
  jaeger_grpc:
    endpoint: jaeger-all-in-one:14250
    sending_queue:
      batch:
  debug:

processors:
  queued_retry:

service:
  pipelines:
    traces:
      receivers: [opencensus]
      exporters: [jaeger_grpc, debug]
      processors: [queued_retry]
