version: "2"
services:

  otel-collector:
    image: omnition/opentelemetry-collector-contrib:latest
    command: ["--config=/conf/collector-config.yaml", "--log-level=DEBUG"]
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "8889:8889"   # Prometheus exporter metrics
      - "55678:55678" # OpenCensus receiver

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
