receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317

exporters:
    logging:

processors:
    batch:

service:
    pipelines:
        metrics:
            receivers: [otlp]
            exporters: [logging]
