receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317

exporters:
    debug:

service:
    pipelines:
        metrics:
            receivers: [otlp]
            exporters: [debug]
