#!/bin/bash
#
# Regenerate the Rust (prost) code for opentelemetry-process-context from the
# process context proto in https://github.com/open-telemetry/opentelemetry-proto
#
# To use, update PROTO_REPO_BRANCH_OR_COMMIT below to the commit hash/tag you want to
# build off of, then run this script and commit the regenerated files.
#
# Requirements: cargo (to install the protoc-gen-prost plugin) and uv/uvx (provides
# protoc via grpcio-tools, similar to the other proto scripts).

# Pinned commit/branch/tag for the process context proto.
PROTO_REPO_BRANCH_OR_COMMIT="023f8cd36cc946617caa9a9e2e9868186f6d22dd"

# protoc-gen-prost release that emits code compatible with the crate's prost 0.13.
PROTOC_GEN_PROST_VERSION="0.4.0"

set -e

PROTO_REPO_DIR=${PROTO_REPO_DIR:-"/tmp/opentelemetry-proto"}
# root of opentelemetry-python repo
repo_root="$(git rev-parse --show-toplevel)"
out_dir="$repo_root/opentelemetry-process-context/rust/src/generated"

# The protos to generate. The process context message imports common and resource.
PROTOS=(
    "opentelemetry/proto/common/v1/common.proto"
    "opentelemetry/proto/resource/v1/resource.proto"
    "opentelemetry/proto/processcontext/v1development/process_context.proto"
)

# Install the prost code generator plugin for protoc.
cargo install "protoc-gen-prost@${PROTOC_GEN_PROST_VERSION}"

# protoc, provided by grpcio-tools via uvx (same approach as scripts/proto_codegen.sh),
# wired up to the cargo-installed prost plugin.
protoc() {
    uvx --from grpcio-tools \
        --python 3.12 \
        python -m grpc_tools.protoc \
        --plugin=protoc-gen-prost="$(command -v protoc-gen-prost)" \
        "$@"
}

protoc --version

# Clone the proto repo if it doesn't exist
if [ ! -d "$PROTO_REPO_DIR" ]; then
    git clone https://github.com/open-telemetry/opentelemetry-proto.git "$PROTO_REPO_DIR"
fi

# Pull in changes and switch to requested branch
(
    cd "$PROTO_REPO_DIR"
    git fetch --all
    git checkout "$PROTO_REPO_BRANCH_OR_COMMIT"
    # pull if PROTO_REPO_BRANCH_OR_COMMIT is not a detached head
    git symbolic-ref -q HEAD && git pull --ff-only || true
)

# Regenerate from scratch.
rm -f "$out_dir"/*.rs
mkdir -p "$out_dir"
protoc \
    -I "$PROTO_REPO_DIR" \
    --prost_out="$out_dir" \
    "${PROTOS[@]}"

# Prepend the standard copyright header
header="// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// @generated by scripts/proto_codegen_process_context.sh from open-telemetry/opentelemetry-proto. DO NOT EDIT."
for f in "$out_dir"/*.rs; do
    printf '%s\n\n%s' "$header" "$(cat "$f")" > "$f"
done

echo "Regenerated prost output in $out_dir"
