# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# The equivalence tests compare two implementations of the same messages:
#   - the pure-Python classes, imported via ``opentelemetry._proto.*``
#   - the real protobuf classes, imported via ``opentelemetry.proto._test.*``
#
# The real classes are generated by protoc and require the ``protobuf`` package
# (installed with the ``opentelemetry-proto[test]`` extra). Guard both sides so
# a comparison can never silently become tautological: the ``_test`` classes
# must be backed by google.protobuf, and the pure-Python classes must not be.
from opentelemetry._proto.trace.v1 import trace_pb2 as _pure_trace_pb2
from opentelemetry.proto._test.trace.v1 import trace_pb2 as _real_trace_pb2

assert type(_real_trace_pb2.Span).__module__.startswith("google"), (
    "opentelemetry.proto._test must provide real protobuf classes; "
    f"Span metaclass came from {type(_real_trace_pb2.Span).__module__}."
)

assert not type(_pure_trace_pb2.Span).__module__.startswith("google"), (
    "opentelemetry._proto must provide the pure-Python classes; "
    f"Span metaclass came from {type(_pure_trace_pb2.Span).__module__}."
)
