name: check-links
on:
  push:
    branches: [ main ]
    paths:
      - '**/*.md'
      - '**/*.rst'
      - '.github/workflows/check-links.yml'
      - '.github/workflows/check_links_config.json'
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.rst'
      - '.github/workflows/check-links.yml'
      - '.github/workflows/check_links_config.json'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  check-links:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'otelbot[bot]' }}
    timeout-minutes: 15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Get changed markdown files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **/*.md
            **/*.rst

      - name: Install markdown-link-check
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm install -g markdown-link-check@v3.12.2

      - name: Run markdown-link-check
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          markdown-link-check \
            --verbose \
            --config .github/workflows/check_links_config.json \
            ${{ steps.changed-files.outputs.all_changed_files }} \
            || { echo "Check that anchor links are lowercase"; exit 1; }