name: "Close stale issues"
on:
  schedule:
    - cron: "12 3 * * *" # arbitrary time not to DDOS GitHub

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue was marked stale due to lack of activity. It will be closed in 30 days.'
        close-issue-message: 'Closed as inactive. Feel free to reopen if this issue needs resolving.'
        exempt-issue-labels: 'feature-request,triaged'
        stale-issue-label: 'backlog'
        days-before-stale: 30
        days-before-close: 60
