name: prepare-release
on:
  push:
    branches:
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Prepare the release
      id: update
      run: |
        ./scripts/prepare_release.sh ${{ steps.get_version.outputs.VERSION }}

    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v2.7.0
      with:
        branch: ${{ steps.get_version.outputs.VERSION }}-auto
        title: '[pre-release] Update changelogs, version [${{ steps.get_version.outputs.VERSION }}]'
      if: ${{ steps.update.outputs.version_updated == 1 }}
