name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Build wheels
      run: ./scripts/build.sh
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        pip install twine
        twine upload --skip-existing --verbose dist/*
  generate_authors:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate Authors
      run: sh ./scripts/generate-authors.sh
    - name: Commit report
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add AUTHORS
        git commit -m "Update authors"
        git push
      continue-on-error: true