name: Shellcheck

on:
  push:
    branches-ignore:
    - 'release/*'
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt update && sudo apt install --assume-yes shellcheck

      - name: Run shellcheck
        run: find . -name \*.sh | xargs shellcheck --severity=warning
